get http://localhost:8000/categories/

###
GET http://localhost:8000/categories/10


###
POST http://localhost:8000/categories/
Content-Type: application/json

{
    "name": "Technology2",
    "slug": "tech2",
    "imgUrl": ""
}
###
DELETE http://localhost:8000/categories/11

###
PUT  http://localhost:8000/categories/10
Content-Type: application/json

{
    "name": "qwe",
    "slug": "qwerty"
}

// Product huseltuud

###
get http://localhost:8000/products/

###
POST  http://localhost:8000/products/
Content-Type: application/json

{
    "name": "mashin",
    "imgUrl": "",
    "createdAt": null
}